# -*- coding: utf-8 -*-
"""VaishnaviKhade_NLP_Lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xM6mXbhbUGcvraFd1WL5aFiQ5Bld288W

**Public Information Machine Translation (EN ↔ HI/MR)**

**Installation & Setup**
"""

# 1. Install required libraries
!pip install -q transformers sentencepiece torch pandas openpyxl

import torch
import pandas as pd
from transformers import MBartForConditionalGeneration, MBart50TokenizerFast

print(f"Setup Complete. GPU Available: {torch.cuda.is_available()}")

"""**Load the AI Model**

We load mBART-50, a transformer-based model. Think of this model as having a "Universal Encoder" that understands the meaning of English and separate "Decoders" for Hindi and Marathi.
"""

# 2. Load the model and tokenizer
model_name = "facebook/mbart-large-50-many-to-many-mmt"
tokenizer = MBart50TokenizerFast.from_pretrained(model_name)
model = MBartForConditionalGeneration.from_pretrained(model_name)

# Use GPU (cuda) for faster processing
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

"""**Generate the Data & Logic**

we define a list of common public info messages. We then create a function that takes these messages and translates them into both target languages.

"""

# A. Generate sample public information data
data = {
    'English_Content': [
        "Please follow the safety guidelines issued by the health department.",
        "Heavy rainfall is expected in the coastal areas tomorrow.",
        "The public library will remain closed on Sunday for maintenance.",
        "Always wear a helmet while riding a motorcycle.",
        "New vaccination centers are opening in your local district."
    ]
}
df = pd.DataFrame(data)

# B. Translation Function
def translate_info(text, target_lang_code):
    tokenizer.src_lang = "en_XX"
    encoded_en = tokenizer(text, return_tensors="pt", padding=True, truncation=True).to(device)

    with torch.no_grad():
        generated_tokens = model.generate(
            **encoded_en,
            forced_bos_token_id=tokenizer.lang_code_to_id[target_lang_code]
        )
    return tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)[0]

"""**Execute Full Translation**

This cell iterates through the generated list and creates new columns for Hindi and Marathi. It uses the apply method, which is the standard way to process dataframes in Python.
"""

# 4. Apply translation to both languages
print("Translating data to Hindi and Marathi... Please wait.")

# Generate Hindi Column
df['Hindi_Translation'] = df['English_Content'].apply(lambda x: translate_info(x, "hi_IN"))

# Generate Marathi Column
df['Marathi_Translation'] = df['English_Content'].apply(lambda x: translate_info(x, "mr_IN"))

print("Translation Complete.")

"""**Display & Save Results**

This displays the final table in the notebook and saves it to an Excel file which you can download from the Colab file explorer on the left.


"""

# 5. Show and Save
# Formatting the output for better readability
pd.set_option('display.max_colwidth', None)
print("\n--- TRANSLATED PUBLIC INFO TABLE ---")
display(df)

# Export to Excel
df.to_excel("Public_Info_Multilingual.xlsx", index=False)
print("\nFile 'Public_Info_Multilingual.xlsx' has been created in your files folder.")